stages:
  - build
  - deploy

build-helm-chart:
  image: alpine/helm:3
  stage: build
  script: 
    - helm package ./momo-store-chart
    - cd /builds/std-ext-006-10/momo-store-infrastructure/
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} https://nexus.praktikum-services.tech/repository/momo-store-std-ext-006-10/ --upload-file momo-store-chart-0.1.0.tgz

deploy-helm-chart:
  stage: deploy
  image: alpine/helm:3
  environment:
    name: test
  script:
    - mkdir -p ~/.kube
    - KUBECONFIG=${CONFIG}
    - echo $CONFIG | base64 -d > ~/.kube/config 
    - chmod 600 ~/.kube/config
    - helm repo add momo-store-std-ext-006-10 ${NEXUS_HELM_REPO} --username ${NEXUS_REPO_USER} --password ${NEXUS_REPO_PASS}
    - helm repo update
    - helm repo list
    - helm upgrade --install momo-store-chart --namespace default momo-store-std-ext-006-10/momo-store-chart --version 0.1.0 --atomic --timeout 15m
    - rm -f ~/.kube/config