apiVersion: v2
name: momo-store-chart
description: A Helm chart for momo-store-cluster
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: backend
    version: 0.1.0
  - name: frontend
    version: 0.1.0
