---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
    rule_files:
       - "/config/*"
    scrape_configs:
    - job_name: kubernetes-pods
      static_configs:
      - targets:  ['momo-backend:8081'] 
        labels:
          group: 'production'
      - targets:  ['localhost:9090'] 
        labels:
          group: 'production'